# coding: utf-8

"""
    АПИ достижений

    Программный интерфейс ачивок для Твой ФФ!

    The version of the OpenAPI document: v2023.08.18
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.reciever_get import RecieverGet  # noqa: E501

class TestRecieverGet(unittest.TestCase):
    """RecieverGet unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RecieverGet:
        """Test RecieverGet
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RecieverGet`
        """
        model = RecieverGet()  # noqa: E501
        if include_optional:
            return RecieverGet(
                user_id = None
            )
        else:
            return RecieverGet(
                user_id = None,
        )
        """

    def testRecieverGet(self):
        """Test RecieverGet"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
