# coding: utf-8

"""
    АПИ достижений

    Программный интерфейс ачивок для Твой ФФ!

    The version of the OpenAPI document: v2023.08.18
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.achievement_api import AchievementApi  # noqa: E501


class TestAchievementApi(unittest.TestCase):
    """AchievementApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AchievementApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_create_achievement_achievement_post(self) -> None:
        """Test case for create_achievement_achievement_post

        Create Achievement  # noqa: E501
        """
        pass

    def test_edit_achievement_achievement_id_patch(self) -> None:
        """Test case for edit_achievement_achievement_id_patch

        Edit Achievement  # noqa: E501
        """
        pass

    def test_get_achievement_achievement_id_get(self) -> None:
        """Test case for get_achievement_achievement_id_get

        Get Achievement  # noqa: E501
        """
        pass

    def test_get_all_achievements_achievement_get(self) -> None:
        """Test case for get_all_achievements_achievement_get

        Get All Achievements  # noqa: E501
        """
        pass

    def test_upload_picture_achievement_id_picture_patch(self) -> None:
        """Test case for upload_picture_achievement_id_picture_patch

        Upload Picture  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
