# coding: utf-8

"""
    АПИ достижений

    Программный интерфейс ачивок для Твой ФФ!

    The version of the OpenAPI document: v2023.08.18
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.reciever_api import RecieverApi  # noqa: E501


class TestRecieverApi(unittest.TestCase):
    """RecieverApi unit test stubs"""

    def setUp(self) -> None:
        self.api = RecieverApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_create_reciever_achievement_achievement_id_reciever_user_id_post(self) -> None:
        """Test case for create_reciever_achievement_achievement_id_reciever_user_id_post

        Create Reciever  # noqa: E501
        """
        pass

    def test_get_all_recievers_achievement_achievement_id_reciever_get(self) -> None:
        """Test case for get_all_recievers_achievement_achievement_id_reciever_get

        Get All Recievers  # noqa: E501
        """
        pass

    def test_revoke_reciever_achievement_achievement_id_reciever_user_id_delete(self) -> None:
        """Test case for revoke_reciever_achievement_achievement_id_reciever_user_id_delete

        Revoke Reciever  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
