# coding: utf-8

"""
    АПИ достижений

    Программный интерфейс ачивок для Твой ФФ!

    The version of the OpenAPI document: v2023.08.18
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.achievement_api_routes_reciever_achievement_get import AchievementApiRoutesRecieverAchievementGet  # noqa: E501

class TestAchievementApiRoutesRecieverAchievementGet(unittest.TestCase):
    """AchievementApiRoutesRecieverAchievementGet unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AchievementApiRoutesRecieverAchievementGet:
        """Test AchievementApiRoutesRecieverAchievementGet
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AchievementApiRoutesRecieverAchievementGet`
        """
        model = AchievementApiRoutesRecieverAchievementGet()  # noqa: E501
        if include_optional:
            return AchievementApiRoutesRecieverAchievementGet(
                id = None,
                name = None,
                description = None,
                picture = None,
                owner_user_id = None,
                recievers = None
            )
        else:
            return AchievementApiRoutesRecieverAchievementGet(
                id = None,
                name = None,
                description = None,
                picture = None,
                owner_user_id = None,
                recievers = None,
        )
        """

    def testAchievementApiRoutesRecieverAchievementGet(self):
        """Test AchievementApiRoutesRecieverAchievementGet"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
