# coding: utf-8

"""
    АПИ достижений

    Программный интерфейс ачивок для Твой ФФ!

    The version of the OpenAPI document: v2023.08.18
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.achievement_edit import AchievementEdit  # noqa: E501

class TestAchievementEdit(unittest.TestCase):
    """AchievementEdit unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AchievementEdit:
        """Test AchievementEdit
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AchievementEdit`
        """
        model = AchievementEdit()  # noqa: E501
        if include_optional:
            return AchievementEdit(
                name = None,
                description = None
            )
        else:
            return AchievementEdit(
                name = None,
                description = None,
        )
        """

    def testAchievementEdit(self):
        """Test AchievementEdit"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
