# coding: utf-8

# flake8: noqa
"""
    АПИ достижений

    Программный интерфейс ачивок для Твой ФФ!

    The version of the OpenAPI document: v2023.08.18
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


# import models into model package
from openapi_client.models.achievement_api_routes_achievement_achievement_get import AchievementApiRoutesAchievementAchievementGet
from openapi_client.models.achievement_api_routes_reciever_achievement_get import AchievementApiRoutesRecieverAchievementGet
from openapi_client.models.achievement_create import AchievementCreate
from openapi_client.models.achievement_edit import AchievementEdit
from openapi_client.models.http_validation_error import HTTPValidationError
from openapi_client.models.reciever_get import RecieverGet
from openapi_client.models.validation_error import ValidationError
